baseurl         = "https://marxinal.github.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Portofolio"
  subtitle    = "Jelena Kalinic"
  cover       = "backgrounddots.jpeg"
  description = "Hello there! Here you will find more about who am I as well as my projects and ongoing research!"
  customCSS = []
  RSSLink = ""

  githubName = "marxinal"

  author = "Jelena Kalinic"
  authorAvatar = "id.jpg"
  authorLocation = "Amsterdam, NL"
  authorWebsite = "https://github.com/marxinal/Projects"
  authorDescription = "Behavioural Data Scientist"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Projects"
  image = "backgrounddots.jpeg"
  url = "/tags/projects/"
  weight = 100



